#!/bin/bash
### App file generated with YoloGen, the Yunohost app generator, version 0.8.3.

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# GENERATE A SECRET KEY
#=================================================

convos_local_secret=$(ynh_string_random --length=30)
ynh_app_setting_set --key=convos_local_secret --value="$convos_local_secret"

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

ynh_hide_warnings /var/www/"$app"/script/convos install

# enable EV module
ynh_hide_warnings /var/www/"$app"/script/convos cpanm EV

mkdir -p "$install_dir/data"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:www-data" "$install_dir"
#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Convos server" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
