#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# GENERATE A SECRET KEY
#=================================================

convos_local_secret=$(ynh_string_random --length=30)
ynh_app_setting_set --key=convos_local_secret --value="$convos_local_secret"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

mkdir -p "$install_dir/data"

#=================================================
# INSTALL CONVOS
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir/script
	ynh_hide_warnings ./convos install
	ynh_hide_warnings ./convos cpanm EV
popd

chown -R "$app:$app" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
#ynh_script_progression "Adding $app's configuration files..."

#ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Convos server" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
